version: '3.9'

services:
  app:
    build:
      context: .
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - 3001:3001

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb
    ports:
      - 27017:27017
    restart: 'always'

volumes:
  mongodb: