version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - app:/home/node/app
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - 3001:3001
    working_dir: /

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: 'always'
volumes:
  app: