name: Node.js Tests
on: 
  push:
    branches: [main]

  pull_request:
    branches: '*' 

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
        
      - name: Install Dependencies
        run: npm install

      - name: Lint Source Files
        run: npm run lint

  test:
    name: Tests
    needs: lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Start mongodb local container
        run: npm run pre-test

      - name: Run Tests
        run: npm test
