name: Node.js CI
on: [pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Lint Source Files
        run: 
          npm ci
          npm run lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test